### ISSUE TITLE
make Fig 3 (robust fig)

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#10]
Fig 3:  Robustness to rotation, translation, scale, outliers
-- consider the trunk example first
-- compare RF variants, including, RF, TF+delta, and rTF+delta (rTF=RobustTylerForest, first passes to the marginal pdf for each variable independently prior to doing anything else, ie, as a pre-processing step.)
-- so, we can 5 situations, (0) the default,  (i) rotate randomly, (ii) also randomly shift each variable, (iii) also randomly rescale each variable, (iv) also randomly add points to each class (eg, sampled uniformly from some unit hypercube).
-- for each of the 5 settings, plot Lhat vs # dimensions for all RF variants

**Comment by jovo** [comment]
Fig 3:  Robustness to scale & translation & rotation & outliers
- compare RF, TF+delta, and rTF+delta
- rTF+delta = RobustLoveFest first passes to the marginal pdf for each variable independently prior to doing anything else, ie, as a pre-processing step.
- so, we can generate data according to some distribution (or use some real data), and (i) rotate randomly, (ii) also randomly shift each variable, (iii) also randomly rescale each variable, (iv) also randomly add points to each class (eg, sampled uniformly from the same).
- thus, we get 5 panels per data setting, the raw data and including each of the transformations, and we plot Lhat vs D for  TF+delta both with & without the pre-processing step
- to start, do this for the multimodal setting.

**Comment by tyler-tomita** [comment]
Rotation, translation, and scaling are all straightforward. I'm a little unclear on how to add outliers. I'm not sure I understand what you mean by sampling uniformly from the same. The outlier model that Carey brings up from time to time is to sample from a Gaussian with the same mean but with greater variance. Is this an acceptable way to do it?

**Comment by jovo** [comment]
sure.
i meant uniform on the unit hypercube,
which is pretty close to big variance gaussian anyway...

On Thursday, March 19, 2015, ttomita notifications@github.com wrote:

>  Rotation, translation, and scaling are all straightforward. I'm a little
> unclear on how to add outliers. I'm not sure I understand what you mean by
> sampling uniformly from the same. The outlier model that Carey brings up
> from time to time is to sample from a Gaussian with the same mean but with
> greater variance. Is this an acceptable way to do it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/10#issuecomment-83726118.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
