### ISSUE TITLE
run LOL variants on rank transformed matrix

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#18]

**Comment by jovo** [comment]
nice! where is the fig?

On Thursday, March 5, 2015, ttomita notifications@github.com wrote:

>  Closed #18 https://github.com/ttomita/DPForest/issues/18.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#event-246908592.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I just put two figs up:

Qing_rank_LOL_loocv.pdf
Qing_rank_pca.pdf - This is the same scatter plot as before but with the unknowns added in per your dad's request

**Comment by tyler-tomita** [comment]
They're in the repo

**Comment by jovo** [comment]
this is great!
let's use LOL (DENL) with k=3.
and make that scatter plot again adding the unknowns.
and this time, see if you can add the discriminant plane.
does that make sense?

On Thu, Mar 5, 2015 at 1:12 PM, ttomita notifications@github.com wrote:

>  They're in the repo
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-77417137.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
It makes sense, but I've only used the loocv function so far. To generate the data for the scatterplot, is it just Proj = LOL(X,Y,types,Kmax) and then project the data onto Proj?

**Comment by jovo** [comment]
Yup!

On Thursday, March 5, 2015, ttomita notifications@github.com wrote:

>  It makes sense, but I've only used the loocv function so far. To
> generate the data for the scatterplot, is it just Proj =
> LOL(X,Y,types,Kmax) and then project the data onto Proj?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-77441008.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
The new scatterplot is up: Qing_rank_LOL.fig. You probably wanna take a look at the .fig file so you can look at it from different angles.

**Comment by jovo** [comment]
so awesome!
can you make the colors: magenta, green, cyan, which are easier for me to
distinguish.
and make the '.' bigger.
if possible, maybe make the plane more transparent? i have no idea whether
that is possible.

how many points are the cancer side?

On Thu, Mar 5, 2015 at 8:03 PM, ttomita notifications@github.com wrote:

>  The new scatterplot is up: Qing_rank_LOL.fig. You probably wanna take a
> look at the .fig file so you can look at it from different angles.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-77486914.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Updated. Indeed you can set the transparency of the plane itself, as well as the transparency of the grid lines on the plane. What do you think?

There are six points on the cancer size, which is still an improvement on what we had before.

**Comment by jovo** [comment]
wow, looking so great!

can you make cancer's X and normal's O
for both the knowns and unknowns, to make it more clear which of the
unknowns are on which side of the line.

and can you make the limits 'tight'?

soooo close right now...

On Fri, Mar 6, 2015 at 5:11 PM, ttomita notifications@github.com wrote:

>  Updated. Indeed you can set the transparency of the plane itself, as
> well as the transparency of the grid lines on the plane. What do you think?
> 
> There are six points on the cancer size, which is still an improvement on
> what we had before.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-77645749.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
ps - i would have made those changes, but when i tried to run
Qing_rank_LOL.m, i got some errors because i haven't set my path like
yours, and you used explicit, rather than relative ranks.

On Fri, Mar 6, 2015 at 5:29 PM, joshua vogelstein jovo@cis.jhu.edu wrote:

> wow, looking so great!
> 
> can you make cancer's X and normal's O
> for both the knowns and unknowns, to make it more clear which of the
> unknowns are on which side of the line.
> 
> and can you make the limits 'tight'?
> 
> soooo close right now...
> 
> On Fri, Mar 6, 2015 at 5:11 PM, ttomita notifications@github.com wrote:
> 
> >  Updated. Indeed you can set the transparency of the plane itself, as
> > well as the transparency of the grid lines on the plane. What do you think?
> > 
> > There are six points on the cancer size, which is still an improvement on
> > what we had before.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ttomita/DPForest/issues/18#issuecomment-77645749.
> 
> ## 
> 
> the glass is all full:  half water, half air.
> openconnecto.me, we're hiring!
> https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
> , jovo.me, my calendar
> https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
My bad. All the code in the repo should have relative paths now. Qing_rank_LOL.m also made calls to some of my own user-defined functions for passing to ranks that you didn't have. Those functions are also in the repo now. 

How does the plot look now?

**Comment by jovo** [comment]
looks great!
i like this view.
do the subjects have ID #'s?
can you put them next to each unknown point?

i vote you do that, find a good angle, and send to my dad & qing.
technically, i'd make the lines thicker, i usually use 'LineWidth',2

super great though, i wonder if this is good enough??!!

[image: Inline image 1]

On Sun, Mar 8, 2015 at 11:49 PM, ttomita notifications@github.com wrote:

>  My bad. All the code in the repo should have relative paths now.
> Qing_rank_LOL.m also made calls to some of my own user-defined functions
> for passing to ranks that you didn't have. Those functions are also in the
> repo now.
> 
> How does the plot look now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-77796518.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Ok. I labeled just the unknowns predicted to be cancer because otherwise the text overwhelms the plot. When I save to pdf for some reason the labels get slightly shifted, but it's still legible.

**Comment by jovo** [comment]
ok, but rotate onto the discriminant plane, right?

On Tue, Mar 10, 2015 at 2:04 PM, ttomita notifications@github.com wrote:

>  Ok. I labeled just the unknowns predicted to be cancer because otherwise
> the text overwhelms the plot. When I save to pdf for some reason the labels
> get slightly shifted, but it's still legible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-78111868.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I changed the view so that it's closer to "sitting on the fence" rather than viewing from one side of the fence. Is that what you mean?

**Comment by jovo** [comment]
definitely better!
but why not just sit right on the fence?
all rotations are just a projection onto a plane.
just project onto the discriminant plane?

On Tue, Mar 10, 2015 at 2:34 PM, ttomita notifications@github.com wrote:

>  I changed the view so that it's closer to "sitting on the fence" rather
> than viewing from one side of the fence. Is that what you mean?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-78117884.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
that makes a lot of sense. it looks pretty good now!

**Comment by jovo** [comment]
perfect! send to dad/qing!

NB: if performance is still not good enough, we can try to limit the
dimensions that we use by discarding those with ratios that go the wrong
way, like we did before...

On Tue, Mar 10, 2015 at 3:49 PM, ttomita notifications@github.com wrote:

>  that makes a lot of sense. it looks pretty good now!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/18#issuecomment-78133324.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
