### ISSUE TITLE
TF+

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#2]
is it doing the version where you sample nnz's from the whole matrix with the same rate as RF does (ie/its downsampling per column, times column), or the other way you originally coded it?

i'd like to know if the 2 methods are sampling from the same distribution in different ways, or slightly different distributions.  if different, i'm curious to see a comparison of the 2 approaches.

**Comment by tyler-tomita** [comment]
TF+ samples nonzeros from the entire matrix at the same rate as RF and places them at random. The original TF generates a random sparse matrix with sparsity of 2/3. Since the latter is much less sparse than the former, the distributions are inherently different, right?

**Comment by jovo** [comment]
there was a previous TF+ that sampled from a poisson with rate 1 for each
feature, right?
that got discontinued in favor of the current TF+ current?
