### ISSUE TITLE
Lhat of Randomer Forest w/ meandiff is lower than Bayes error

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#23]
I estimated the Bayes error using the Bayes optimal classifier on the sampled data points. The estimated curve matches up with the analytical curve. Compare Trunk_bayes_error_vs_d.pdf (analytical) and Trunk_bayes_error_est.pdf (estimated). I'm fairly confident the curve is correct, but could you send me your code for generating the Bayes error? 

I think it has to do with getting poor estimates of the means when n < d. I'm running some tests at n=10000 and d=1000 to confirm.

**Comment by jovo** [comment]
hm, they do look similar.
but is our stuff still doing better than bayes error?
if so, there is a bug somewhere...

my code is:

```
    Yhat = gmm_predict(Xtest,Ytest,P);
```

gmm_predict is in helper functions.

post an issue if you don't understand something, it is not commented at all
i am realizing...

On Fri, Mar 6, 2015 at 5:46 PM, ttomita notifications@github.com wrote:

>  I estimated the Bayes error using the Bayes optimal classifier on the
> sampled data points. The estimated curve matches up with the analytical
> curve. Compare Trunk_bayes_error_vs_d.pdf (analytical) and
> Trunk_bayes_error_est.pdf (estimated). I'm fairly confident the curve is
> correct, but could you send me your code for generating the Bayes error?
> 
> I think it has to do with getting poor estimates of the means when n < d.
> I'm running some tests at n=10000 and d=1000 to confirm.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Awesome thanks! I am fairly confident now that the Bayes error is correct. I'm also not 100% sure that there is a bug in the Randomer Forest code. I ran Randomer Forest w/ meandiff again but with n=10000. I also ran LDA at n=10000. Both are right at Bayes error, which suggests that the drop below Bayes error for Randomer Forest w/ meandiff when n=100 is simply a result of low sample size.

Take a look at the plot called Trunk_Lhat_vs_d_with_LDA_n10000.pdf

**Comment by jovo** [comment]
n is the # of what? training samples? test samples? trees?

in any case, that LDA and RandomerForest agree with Bayes for n=10,000 is
compelling.

when n=100, low sample size does not mean that it can beat bayes error.
so, i'm still confused...

On Mon, Mar 9, 2015 at 2:13 AM, ttomita notifications@github.com wrote:

>  Awesome thanks! I am fairly confident now that the Bayes error is
> correct. I'm also not 100% sure that there is a bug in the Randomer Forest
> code. I ran Randomer Forest w/ meandiff again but with n=10000. I also ran
> LDA at n=10000. Both are right at Bayes error, which suggests that the drop
> below Bayes error for Randomer Forest w/ meandiff when n=100 is simply a
> result of low sample size.
> 
> Take a look at the plot called Trunk_Lhat_vs_d_with_LDA_n10000.pdf
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-77805187.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
one thing you could do, assuming n=# training samples, 
is run RandomerForest (sparse+mean diff) with n=100 several times, and see whether you are just poorly capturing the variance?

**Comment by tyler-tomita** [comment]
What you see in Fig1 (which is now updated) is the result of averaging of 10 trials, where in each trial a different set of 100 points was sampled. Is that what you mean?

**Comment by jovo** [comment]
that is what i mean.
i don't understand why we are still doing better than bayes error.
i assume if there is no bug in bayes error,
there is possibly a bug in how you compute error from RF?

On Tue, Mar 10, 2015 at 12:07 PM, ttomita notifications@github.com wrote:

>  What you see in Fig1 (which is now updated) is the result of averaging
> of 10 trials, where in each trial a different set of 100 points was
> sampled. Is that what you mean?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-78086440.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I'm looking into this...

**Comment by jovo** [comment]
great.

On Tue, Mar 10, 2015 at 2:04 PM, ttomita notifications@github.com wrote:

>  I'm looking into this...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-78112040.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I can't seem to find any bugs in computing the error. I think what's happening is basically explained in the following figure I just made: Trunk_mean_difference_projection.pdf. This shows the projection of the data onto the mean difference vector for different values of d at fixed n. The trend is basically that the two classes get more separated as the ratio of d to n gets large. At some point, the data can be perfectly separated, which is why we see Lhat for randomer forest w/ mean diff go to zero.

**Comment by jovo** [comment]
ah, that is beautiful!
so bayes error must go to zero, right?

can you point me to the code where you compute error (for bayes and others)?
i'll look at them...

On Thu, Mar 12, 2015 at 4:53 PM, ttomita notifications@github.com wrote:

>  I can't seem to find any bugs in computing the error. I think what's
> happening is basically explained in the following figure I just made:
> Trunk_mean_difference_projection.pdf. This shows the projection of the data
> onto the mean difference vector for different values of d at fixed n. The
> trend is basically that the two classes get more separated as the ratio of
> d to n gets large. At some point, the data can be perfectly separated,
> which is why we see Lhat for randomer forest w/ mean diff go to zero.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-78612281.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Bayes Error doesn't go to zero. Look at the case when n=1000, d=1000 here: Trunk_mean_difference_projection_n1000.pdf. 

The function oobpredict() in rpclassificationforest2.m is used to compute Yhat and Lhat for Randomer Forest. The script Trunk_bayes_error.m was used to compute bayes error analytically.

**Comment by jovo** [comment]
but by definition, you can't do better than bayes error.
so, if our classifier is beating bayes error, something is wrong.

On Thursday, March 12, 2015, ttomita notifications@github.com wrote:

>  Bayes Error doesn't go to zero. Look at the case when n=1000, d=1000
> here: Trunk_mean_difference_projection_n1000.pdf.
> 
> The function oobpredict() in rpclassificationforest2.m is used to compute
> Yhat and Lhat for Randomer Forest. The script Trunk_bayes_error.m was used
> to compute bayes error analytically.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-78655352.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I figured out what's happening. It's quite simple and I should've caught this earlier. Suppose you have a set of training data Xtrain. When you compute the estimated mean difference vector, which we will call mdhat and project Xtrain onto that, you obtain very good separation between classes. Next project Xtrain onto the true mean difference vector, md_0, and you still see good separation, but not quite as good as the previous. Now project a new set of data Xtest onto mdhat, which was estimated using Xtrain, and you see significantly less optimistic separation. You can see this in the figure Trunk_mean_difference_projection_v2.pdf.

So what's happening in my algorithm is that a single mean difference is computed using ALL of the n=100 samples and then is used for all trees. What I should be doing is estimating the mean difference using only the in bag samples for each tree. I need to reanalyze all of the datasets with the updated code. We should expect to see less optimistic (but hopefully still promising!) results.

**Comment by jovo** [comment]
interesting. ok, good catch, but that algorithm should not beat bayes error
either, right?

On Friday, March 13, 2015, ttomita notifications@github.com wrote:

>  I figured out what's happening. It's quite simple and I should've caught
> this earlier. Suppose you have a set of training data Xtrain. When you
> compute the estimated mean difference vector, which we will call mdhat and
> project Xtrain onto that, you obtain very good separation between classes.
> Next project Xtrain onto the true mean difference vector, md_0, and you
> still see good separation, but not quite as good as the previous. Now
> project a new set of data Xtest onto mdhat, which was estimated using
> Xtrain, and you see significantly less optimistic separation. You can see
> this in the figure Trunk_mean_difference_projection_v2.pdf.
> 
> So what's happening in my algorithm is that a single mean difference is
> computed using ALL of the n=100 samples and then is used for all trees.
> What I should be doing is estimating the mean difference using only the in
> bag samples for each tree. I need to reanalyze all of the datasets with the
> updated code. We should expect to see less optimistic (but hopefully still
> promising!) results.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-79433892.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
The newly proposed algorithm should not be Bayes Error. I'm certain of that. The original algorithm is, in a sense, cheating because it's using the transformation learned by all training data and then applying that to predict on the out of bag samples, which were part of the samples used in learning the transformation. I'm quite confident that if instead of out-of-bag error, I compute error on an entirely new set of samples using the original implementation of Randomer Forest w/ mean diff, the error will not be better than Bayes. I'm confirming this now.

**Comment by jovo** [comment]
ah. brilliant. excited to see it!

On Friday, March 13, 2015, ttomita notifications@github.com wrote:

>  The newly proposed algorithm should not be Bayes Error. I'm certain of
> that. The original algorithm is, in a sense, cheating because it's using
> the transformation learned by all training data and then applying that to
> predict on the out of bag samples, which were part of the samples used in
> learning the transformation. I'm quite confident that if instead of
> out-of-bag error, I compute error on an entirely new set of samples using
> the original implementation of Randomer Forest w/ mean diff, the error will
> not be better than Bayes. I'm confirming this now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-79530818.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Here is the new plot for Randomer Forest w/ mean diff using the new code where the mean difference is estimated for each tree using only the in-bag samples: Trunk_ooberror_vs_d_meandiff_v2_n100_var1_embed1000_ntrees10_ntrials.pdf

This is exactly what Trunk talks about in his 1979 paper: "A simple problem has been formulated where the probability of error approaches zero as the dimensionality increases and ALL PARAMETERS ARE KNOWN (here he is referring to the case mu(i) = (1/i)^k and k=1/2, but i'm using k=1 which makes the error approach 0.1); on the other hand, the probability of error approaches one-half as the dimensionality increases and PARAMETERS ARE ESTIMATED."

I can think of one potential way to alleviate this. If we could compute variable importance and weight each dimension of the mean difference vector accordingly, then I think the mean difference projection will perform better. What do you think?

**Comment by jovo** [comment]
new figure looks much better!
i don't want to start improving the algorithm until we understand its
properties better...

On Fri, Mar 13, 2015 at 11:34 PM, ttomita notifications@github.com wrote:

>  Here is the new plot for Randomer Forest w/ mean diff using the new code
> where the mean difference is estimated for each tree using only the in-bag
> samples:
> Trunk_ooberror_vs_d_meandiff_v2_n100_var1_embed1000_ntrees10_ntrials.pdf
> 
> This is exactly what Trunk talks about in his 1979 paper: "A simple
> problem has been formulated where the probability of error approaches zero
> as the dimensionality increases and ALL PARAMETERS ARE KNOWN (here he is
> referring to the case mu(i) = (1/i)^k and k=1/2, but i'm using k=1 which
> makes the error approach 0.1); on the other hand, the probability of error
> approaches one-half as the dimensionality increases and PARAMETERS ARE
> ESTIMATED."
> 
> I can think of one potential way to alleviate this. If we could compute
> variable importance and weight each dimension of the mean difference vector
> accordingly, then I think the mean difference projection will perform
> better. What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/23#issuecomment-79789171.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
