### ISSUE TITLE
check 2D vs 3D LOL

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#24]
learn 2D & 3D LOL (DENL) on the training data.
embed and classify the test data.
check and see whether the class predictions disagree at all.
if not, just plot the 2D variant?

**Comment by tyler-tomita** [comment]
There is one less unknown data point predicted as cancer in 2D than in 3D, so let's stick with 3D?

**Comment by jovo** [comment]
ok

On Monday, March 9, 2015, ttomita notifications@github.com wrote:

>  There is one less unknown data point predicted as cancer in 2D than in
> 3D, so let's stick with 3D?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/24#issuecomment-77799767.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
