### ISSUE TITLE
Fig 4a: benchmark in real data

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#27]
apply RF variants to data in the mega classifier survey:
http://jmlr.org/papers/volume15/delgado14a/delgado14a.pdf
this will give us a good understanding of our relative performance in a wide variety of settings

maybe make a scatterplot of performance on y-axis vs. ratio D/n?
different variants of RF get different color/symbols

**Comment by jovo** [comment]
left panel: mean & 1-std level set of 2D gaussian estimate of performance for all K algs.
right panel: scatter plot of Lhat(RF) vs Lhat(TF)
(note that we need to optimize all variants the same, to compare fairly)

**Comment by tyler-tomita** [comment]
Left panel: Fig4_Real_Data_Panel_A.pdf
Right panel: Fig4_Real_Data_Panel_B.pdf

The standard deviation for Lhats and Times are really large... Thoughts?

For the right panel, I indicated relative distance to the line at which Lhat_RF = Lhat_RobustRandomerForest using a blue-to-red color map. Red means farther away. You can clearly see more cases in which RandomerForest beats RF.

**Comment by jovo** [comment]
> The standard deviation for Lhats and Times are really large... Thoughts?
> 
> these are level sets.  you seem to be plotting 1 std level set?
> plot 0.1 std level set?
> 
> For the right panel, I indicated relative distance to the line at which
> Lhat_RF = Lhat_RobustRandomerForest using a blue-to-red color map. Red
> means farther away. You can clearly see more cases in which RandomerForest
> beats RF.

ok, well, the results are amazing!
i don't quite understand the color map.
i'm really curious about that set where we are killing RF.
are they high dimension? large sample size?

maybe encoding # of ambient dimensions in the marker size,
and color indicating # of samples, or something, would be good?

> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/27#issuecomment-98889332.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Good suggestion. I'll also make one where color indicates ratio of n/d

**Comment by jovo** [comment]
ok.  and maybe size is n or d?
can you explain the colors that you used?
does it carry some other info?

On Tue, May 5, 2015 at 7:21 PM, ttomita notifications@github.com wrote:

>  Good suggestion. I'll also make one where color indicates ratio of n/d
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/27#issuecomment-99259586.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
The colors I used just indicated the distance from the line where Lhat_RF = Lhat. Blue indicates on the line, red indicates far from the line. So a red point would mean one classifier performs much better than the other. It's kinda redundant. I think using the colors and size to indicate something about the dataset conveys more information.

**Comment by jovo** [comment]
ok, thanks.

On Tue, May 5, 2015 at 10:42 PM, ttomita notifications@github.com wrote:

>  The colors I used just indicated the distance from the line where
> Lhat_RF = Lhat. Blue indicates on the line, red indicates far from the
> line. So a red point would mean one classifier performs much better than
> the other. It's kinda redundant. I think using the colors and size to
> indicate something about the dataset conveys more information.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/27#issuecomment-99299433.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
