### ISSUE TITLE
Fig 1: at least for parity, add some D's between 50 & 100

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#31]
Trunk go to zero
Parity better than chance for low d

**Comment by tyler-tomita** [comment]
Fig1 is updated. Randomer Forest w/ mean diff does awesome in the updated Trunk example. Makes sense since the dimensions are losing information at a slower rate.

**Comment by jovo** [comment]
NICE!!!

On Thursday, March 26, 2015, ttomita notifications@github.com wrote:

>  Fig1 is updated. Randomer Forest w/ mean diff does awesome in the
> updated Trunk example. Makes sense since the dimensions are losing
> information at a slower rate.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/31#issuecomment-86704913.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
i can't get into github from airport:
so, i'll just comment here and you can make new issues:

1) why does bayes error go up before it goes down in parity example?
i'm guessing this is just sample error, but it is concerning.

2) did you change the dense version yet to only keep the relevant dimension?

3) let's make sure we have an issue to make the even randomer version,
where we have gaussians centered at -1 & 1

4) in parity, sparse w/o mean diff seems to win when dimension is low, not
sure why, maybe rounding errors?
maybe make it even easier?

5) transformations to consider for fig 3: nothing, rotation, rigid, affine,
outliers.
i think maybe plot Lhat vs. ambient # of dimensions,
but each panel has 1 algorithm, all 4 different conditions, to show
invariance for the different methods.

cool?

On Thursday, March 26, 2015, ttomita notifications@github.com wrote:

>  Fig1 is updated. Randomer Forest w/ mean diff does awesome in the
> updated Trunk example. Makes sense since the dimensions are losing
> information at a slower rate.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/31#issuecomment-86704913.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
Fig1 is looking way better.
what values did you use for ambient dimensions?
seems like ... 10, 50, 100...?
i think it will look better if you add 60,70,80,90, or at least 75, at least for parity example.

**Comment by tyler-tomita** [comment]
Yeah i just did logspace(log10(2),3,5) which is [2,9,45,211,1000]. I'll throw in some more intermediate values for D.

**Comment by jovo** [comment]
ah. yah, try 7 or more and see if it looks better...

On Friday, April 3, 2015, ttomita notifications@github.com wrote:

>  Yeah i just did logspace(log10(2),3,5) which is [2,9,45,211,1000]. I'll
> throw in some more intermediate values for D.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/31#issuecomment-89400987.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
