### ISSUE TITLE
Fig 2 Changes

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#32]
Profile code at high d and see what step is taking longer in Randomer Forest

**Comment by tyler-tomita** [comment]
Randomly generating a 1000 dimensional sparse matrix and projecting X onto it is what causes Randomer Forest to take ~1.5x longer than Random Forest. It's the matrix generation that actually takes the longest, not the multiplication.

**Comment by jovo** [comment]
interesting and good to note.
have you started a tex file of the manuscript yet?
if not, now is a good time to start.
just make new folder in github repo.
just include figs for now.
and temporary captions (including for example, explaining this)

and we can start placing background ref's in there too.
maybe make a new issue for this?

On Thursday, March 26, 2015, ttomita notifications@github.com wrote:

>  Randomly generating a 1000 dimensional sparse matrix and projecting X
> onto it is what causes Randomer Forest to take ~1.5x longer than Random
> Forest. It's the matrix generation that actually takes the longest, not the
> multiplication.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/32#issuecomment-86720072.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
is fig2 now using the code that only keeps the necessary stuff? that will change timing a lot, potentially?
