### ISSUE TITLE
Fig 3 Changes

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#33]
Sample scaling factor from 0-10 instead of 0-2
Try rotation + scaling
Determine if rotational invariance is solely due to the mean difference vector by examining parity at low d, in which Randomer Forest should not find the mean difference vector to be a useful dimension for splitting

**Comment by tyler-tomita** [comment]
Fig 3 is updated (Fig3_Invariance_v2.pdf) so that each panel has one algorithm compared across all different conditions. For expansion/dilation, I allowed the scaling factor to be sampled from U(0,10) instead of U(0,2). Now there is a noticeable drop in performance in the non-robust version when Trunk is scaled, while the robust version is unaffected by scaling.

 I wasn't entirely sure what you meant by affine because affine encompasses a variety of transformations and is not mutually exclusive with the set of rigid transformations. So for affine I did a rotation followed by expansion/dilation.

**Comment by jovo** [comment]
this is so awesome!!!!!!
let's only do: untransformed, rotated, affine, and outlier.
also, let's keep the y-axis consistent across all of the panels.
also, let's add LOL, which is basically optimized for the trunk setting.
for now, for simplicity, let's keep LOL using k dimensions.
if you tell me how many samples you are using, i will tell you the optimal k
(or you can check yourself).

this figure is a huge and awesome win!!!

**Comment by jovo** [comment]
just to clarify, we'll add a 4th column for LOL.
