### ISSUE TITLE
Bayes error for parity increases at d=10 and then drops

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#35]
There was an issue in the way I was sampling. Fig 1 is updated with the fixed Bayes Error and Lhats, which didn't change much.

**Comment by jovo** [comment]
the fig1 i see still have bayes error going up and then back down...

On Thu, Apr 2, 2015 at 3:50 PM, ttomita notifications@github.com wrote:

>  There was an issue in the way I was sampling. Fig 1 is updated with the
> fixed Bayes Error and Lhats, which didn't change much.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/35.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
doesn't seem like github got updated?

On Thu, Apr 2, 2015 at 10:46 PM, joshua vogelstein jovo@cis.jhu.edu wrote:

> the fig1 i see still have bayes error going up and then back down...
> 
> On Thu, Apr 2, 2015 at 3:50 PM, ttomita notifications@github.com wrote:
> 
> >  There was an issue in the way I was sampling. Fig 1 is updated with the
> > fixed Bayes Error and Lhats, which didn't change much.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ttomita/DPForest/issues/35.
> 
> ## 
> 
> the glass is all full:  half water, half air.
> openconnecto.me, jovo.me, my calendar
> https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
or, seems like it did, but figs didn't?

On Thu, Apr 2, 2015 at 10:47 PM, joshua vogelstein jovo@cis.jhu.edu wrote:

> doesn't seem like github got updated?
> 
> On Thu, Apr 2, 2015 at 10:46 PM, joshua vogelstein jovo@cis.jhu.edu
> wrote:
> 
> > the fig1 i see still have bayes error going up and then back down...
> > 
> > On Thu, Apr 2, 2015 at 3:50 PM, ttomita notifications@github.com wrote:
> > 
> > >  There was an issue in the way I was sampling. Fig 1 is updated with
> > > the fixed Bayes Error and Lhats, which didn't change much.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ttomita/DPForest/issues/35.
> > 
> > ## 
> > 
> > the glass is all full:  half water, half air.
> > openconnecto.me, jovo.me, my calendar
> > https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> 
> ## 
> 
> the glass is all full:  half water, half air.
> openconnecto.me, jovo.me, my calendar
> https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
That's weird... I see the updated Fig1 when I click the link to the pdf file from the Github site.

**Comment by jovo** [comment]
updated now, i'll comment on the issues...

On Fri, Apr 3, 2015 at 2:39 PM, ttomita notifications@github.com wrote:

>  That's weird... I see the updated Fig1 when I click the link to the pdf
> file from the Github site.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/35#issuecomment-89385623.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
