### ISSUE TITLE
Update Randomer Forest so that only the split dimension for each node is stored

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#36]
Done. Makes a world of difference. To give you an idea, for Trunk n=100, d=1000, an instantiation of dense randomer forest is only about 4x larger than that of random forest. Previously, it was a few orders of magnitude larger.

**Comment by jovo** [comment]
nice! I presume performance is the same?

On Thursday, April 2, 2015, ttomita notifications@github.com wrote:

>  Done. Makes a world of difference. To give you an idea, for Trunk n=100,
> d=1000, an instantiation of dense randomer forest is only about 4x larger
> than that of random forest. Previously, it was a few orders of magnitude
> larger.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/36.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
