### ISSUE TITLE
Fig1 Try Spiral

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#42]

**Comment by tyler-tomita** [comment]
Plotted Lhat vs D for D up to 10: Spiral_ooberror_vs_d_n100_ntrees1000_ntrials10.pdf

**Comment by jovo** [comment]
we seem to be marginally better, not impressively so.
i wonder if there are other parameter regimes where the difference is more
stark?
do you feel like investigating?

On Mon, May 4, 2015 at 8:06 PM, ttomita notifications@github.com wrote:

>  Plotted Lhat vs D for D up to 10:
> Spiral_ooberror_vs_d_n100_ntrees1000_ntrials10.pdf
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/42#issuecomment-98888586.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Sure, I can sweep over various increments for the angles and the radius and see what I find

**Comment by jovo** [comment]
cool

On Tue, May 5, 2015 at 7:18 PM, ttomita notifications@github.com wrote:

>  Sure, I can sweep over various increments for the angles and the radius
> and see what I find
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/42#issuecomment-99258349.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
