### ISSUE TITLE
rapid fire fig changes

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#43]
throughout:
- all lines thicker
- Change names to "R'er F(dense)", "R'er F(sparse)", "R'er F (sparse+delta)" (may need to abbreviate 'dense' and 'spase' with 'd' and 's'

fig 1 (top row):
- Lhat only on far left axis
- parity xlabel on linear (not log) scale
- add robust alg
- add (A), (B), and (C) to title of 'trunk', 'parity' and multimodal', respectively

fig 1 (bottom row):
- change axis labels to 'ambient dimension 1' and 'ambient dimension 2'

fig 2:
- add robust
- add (A), (B), and (C) to title of 'trunk', 'parity' and multimodal', respectively

fig 3:
- add (A), (B), and (C) to titles

fig 4:
- add titles
- B x- and y-labels are wrong
- seems like the colorbar is all red, can you make it a log scale?

**Comment by tyler-tomita** [comment]
What do you think now? I still need to add robust into figs 1 and 2.

For fig 4, the colorbar was already log scale, which is why it looks mostly red. If you look closely, it starts out blue at the bottom then rapidly changes to red.

**Comment by jovo** [comment]
way better!
i see that it starts out blue at the bottom.
i want the color to change on a log scale
(eg, colorbar should have ticks at 10, 25, 50, 100, 200).

let's make a new issue for anything that involves running more code.
i wanna get a draft with everything that we have for now.
once we have that, we can add some more results.

On Tue, May 12, 2015 at 5:14 AM, ttomita notifications@github.com wrote:

>  What do you think now? I still need to add robust into figs 1 and 2.
> 
> For fig 4, the colorbar was already log scale, which is why it looks
> mostly red. If you look closely, it starts out blue at the bottom then
> rapidly changes to red.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/43#issuecomment-101205561.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
