### ISSUE TITLE
fig captions

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#44]
make legend for fig 1 first.
once you get the basic idea of how to make a legend, we'll make the others.

**Comment by tyler-tomita** [comment]
I'm not sure what you mean. There are already legends accompanying each of the figures. Did you mean captions?

**Comment by jovo** [comment]
yah, captions, sorry.

On Tue, May 12, 2015 at 5:17 AM, ttomita notifications@github.com wrote:

>  I'm not sure what you mean. There are already legends accompanying each
> of the figures. Did you mean captions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/44#issuecomment-101206485.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I added captions to the four figs. I wasn't really sure how much detail I needed to go into...

**Comment by jovo** [comment]
Figure 1 caption:

Classification performance comparing Random Forest (RF) to several variants
of Randomer Forest (R'er F), and Bayes optimal performance, on three
distinct simulation settings: (A) Trunk, (B) Parity, and (C) Multimodal
(see Methods for details).  For all settings, the top panel depicts
misclassification rate vs. the number of ambient (coordinate) dimensions,
and the bottom panel shows a 2D scatter plot of the first 2 coordinates
(dashed circles denote the standard deviation level set).  Note that in all
settings, for all number of dimensions, R'er F outperforms RF, even Trunk
and Parity, which were designed specifically for RF because the
discriminant boundary naturally lies along the coordinate basis.

try caption 2 and see what you get, and i'll fix.

thanks.

On Tue, May 12, 2015 at 10:04 AM, ttomita notifications@github.com wrote:

>  I added captions to the four figs. I wasn't really sure how much detail
> I needed to go into...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/44#issuecomment-101294920.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
How about this for caption 2:

Classifier training time comparing Random Forest (RF) to several variants of Randomer Forest (R'er F) on three distinct simulation settings: (A) Trunk, (B) Parity, and (C) Multimodal (see Methods for details).  For all settings, the panels depict training time (in seconds) vs. the number of ambient (coordinate) dimensions. The increase in training time for the R'er F variants can mostly be attributed to random sampling of projection matrices.

**Comment by jovo** [comment]
Classifier training time comparing RF to several variants of RerF, same
setting as the top row of Figure 1.  The only difference is that the y-axis
here labels training time (in seconds).  Although RerF requires slightly
more time than RF (largely due to random sampling of projection matrices),
they scale similarly.

On Tue, May 12, 2015 at 1:59 PM, ttomita notifications@github.com wrote:

>  How about this for caption 2:
> 
> Classifier training time comparing Random Forest (RF) to several variants
> of Randomer Forest (R'er F) on three distinct simulation settings: (A)
> Trunk, (B) Parity, and (C) Multimodal (see Methods for details). For all
> settings, the panels depict training time (in seconds) vs. the number of
> ambient (coordinate) dimensions. The increase in training time for the R'er
> F variants can mostly be attributed to random sampling of projection
> matrices.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/44#issuecomment-101366302.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
