### ISSUE TITLE
fig 3: add 4th column for LOL (after finalizing other fig stuff)

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#45]

**Comment by jovo** [comment]
will u send me an email when you've  updated figs running the corrected
version?

and maybe another one with the faster version?

or you decide what makes the most sense.

On Thursday, May 28, 2015, ttomita notifications@github.com wrote:

>  Closed #45 https://github.com/ttomita/DPForest/issues/45.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/45#event-316407954.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I'll let you know when the faster one is done

**Comment by tyler-tomita** [comment]
All of the figures except for figure 4 are updated with the fast code. Even
with the faster code, it still takes a while to run the benchmark datasets.
I've also included the modified Trunk as figure A1.

On Thu, May 28, 2015 at 2:33 PM, joshua vogelstein <notifications@github.com

> wrote:
> 
> will u send me an email when you've updated figs running the corrected
> version?
> 
> and maybe another one with the faster version?
> 
> or you decide what makes the most sense.
>

**Comment by jovo** [comment]
did u push?
they look the same?
GitHub says last push was last night?

On Friday, May 29, 2015, ttomita notifications@github.com wrote:

>  All of the figures except for figure 4 are updated with the fast code.
> Even
> with the faster code, it still takes a while to run the benchmark datasets.
> I've also included the modified Trunk as figure A1.
> 
> On Thu, May 28, 2015 at 2:33 PM, joshua vogelstein <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> 
> > wrote:
> > 
> > will u send me an email when you've updated figs running the corrected
> > version?
> > 
> > and maybe another one with the faster version?
> > 
> > or you decide what makes the most sense.
> > 
> > On Thursday, May 28, 2015, ttomita <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > Closed #45 https://github.com/ttomita/DPForest/issues/45.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ttomita/DPForest/issues/45#event-316407954.
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ttomita/DPForest/issues/45#issuecomment-106556354.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/45#issuecomment-106813048.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I pushed. If you look at the nips2015_tyler.pdf you see that classification
performance is basically the same as previously and training time of RerF
is now nearly identical to RF

**Comment by jovo** [comment]
fig 3 is unchanged?

lets add fig0 as an appendix fig for now too.
sorry we didn't finish yet
lets continue working hard
we should be finished soon

On Friday, May 29, 2015, ttomita notifications@github.com wrote:

>  I pushed. If you look at the nips2015_tyler.pdf you see that
> classification
> performance is basically the same as previously and training time of RerF
> is now nearly identical to RF
> 
> On Fri, May 29, 2015 at 11:21 AM, joshua vogelstein <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > did u push?
> > they look the same?
> > GitHub says last push was last night?
> > 
> > On Friday, May 29, 2015, ttomita <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > All of the figures except for figure 4 are updated with the fast code.
> > > Even
> > > with the faster code, it still takes a while to run the benchmark
> > > datasets.
> > > I've also included the modified Trunk as figure A1.
> > > 
> > > On Thu, May 28, 2015 at 2:33 PM, joshua vogelstein <
> > > notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > 
> > > > wrote:
> > > > 
> > > > will u send me an email when you've updated figs running the
> > > > corrected
> > > > version?
> > > > 
> > > > and maybe another one with the faster version?
> > > > 
> > > > or you decide what makes the most sense.
> > > > 
> > > > On Thursday, May 28, 2015, ttomita <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > > 
> > > > > Closed #45 https://github.com/ttomita/DPForest/issues/45.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/ttomita/DPForest/issues/45#event-316407954.
> > > > 
> > > > ## 
> > > > 
> > > > the glass is all full: half water, half air.
> > > > openconnecto.me, jovo.me, office hours
> > > > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/ttomita/DPForest/issues/45#issuecomment-106556354
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ttomita/DPForest/issues/45#issuecomment-106813048
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ttomita/DPForest/issues/45#issuecomment-106844231.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/45#issuecomment-106845352.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Ok. Still waiting on benchmarks

On Fri, May 29, 2015 at 9:17 PM, joshua vogelstein <notifications@github.com

> wrote:
> 
> fig 3 is unchanged?
> 
> lets add fig0 as an appendix fig for now too.
> sorry we didn't finish yet
> lets continue working hard
> we should be finished soon
>
