### ISSUE TITLE
final code things to run

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#47]
- fig 1: robust RerF
- fig 2: robust RerF
- fig 3: add fisherfaces (not lol, since we can't cite lol yet)
- fig 3: add another row for parity simulation

**Comment by tyler-tomita** [comment]
RF and all RerFs do better when parity is rotated. I'm confused...

**Comment by jovo** [comment]
awesome. show me?

On Fri, May 15, 2015 at 12:55 PM, ttomita notifications@github.com wrote:

>  RF and all RerFs do better when parity is rotated. I'm confused...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/47#issuecomment-102458115.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
lower panels (E-H) of Fig3_Invariance_v2 are parity

**Comment by jovo** [comment]
woah. so cool.
can you put grids on, so we can see stuff more clearly?

On Fri, May 15, 2015 at 1:38 PM, ttomita notifications@github.com wrote:

>  lower panels (E-H) of Fig3_Invariance_v2 are parity
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/47#issuecomment-102465697.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
