### ISSUE TITLE
fig 5: analysis of performance vs. RF

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#48]
i wanna try to understand when we are doing better.
for that reason, i want a fig (doesn't need to be pretty now),
1 row, 5 columns.
y-axis: Lhat(R'erF(s+d+r)) - Lhat(RF)
x-axis:
1) D
2) n
3) n/D
4) Lhat(naive bayes classifier), in matlab 'classify' with the type set to 'diaglinear' does it, and so does the 'naive bayes' method.

**Comment by tyler-tomita** [comment]
for naive bayes Lhat, should I do loocv?

**Comment by jovo** [comment]
i guess so.

On Tue, May 12, 2015 at 5:40 PM, ttomita notifications@github.com wrote:

>  for naive bayes Lhat, should I do loocv?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/48#issuecomment-101429531.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
I saved each panel to a different file (Fig5_panel_#). The relationship between LhatRF_delta and n and d is very weak. There also seems to be a slight negative correlation between LhatRF_delta and LhatNB

**Comment by jovo** [comment]
can you plot the first 3 panels on a log scale for the x-axis so we can see
things better?
we should also think about how to quantify sparsity of the discriminant
boundary, which might matter...

On Fri, May 15, 2015 at 12:44 PM, ttomita notifications@github.com wrote:

>  Reopened #48 https://github.com/ttomita/DPForest/issues/48.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/48#event-306008351.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
It's log scale now. 
What is meant by sparsity of the discriminant boundary? Is that like a measure of how much each dimension contributes to the discriminant boundary?

**Comment by jovo** [comment]
interesting. can you add a regression line?

sparsity of the discriminant boundary means something like "how well can we
do only using k ambient dimensions?"
not sure what is the right way to quantify this.
i'm just trying to figure out when RerF beats RF...

On Fri, May 15, 2015 at 1:50 PM, ttomita notifications@github.com wrote:

>  It's log scale now.
> What is meant by sparsity of the discriminant boundary? Is that like a
> measure of how much each dimension contributes to the discriminant boundary?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/48#issuecomment-102470409.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
