### ISSUE TITLE
R'er F vs. RerF (pronounced 'rerf')

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#49]
what do you think about changing the acronym everywhere to "RerF"?

**Comment by tyler-tomita** [comment]
I didn't like the apostrophe :)

**Comment by jovo** [comment]
you gotta tell me these things!
this is your baby, i am just making suggestions :-)

On Fri, May 15, 2015 at 12:29 PM, ttomita notifications@github.com wrote:

>  I didn't like the apostrophe :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/49#issuecomment-102453464.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
