### ISSUE TITLE
1-sided mann-whitney test comparing RF vs. RerF(s+d+r) on benchmark data

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#52]
http://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test

**Comment by tyler-tomita** [comment]
Wouldn't the signed rank test be more powerful since the Lhats are paired?

**Comment by jovo** [comment]
good call!

On Fri, May 15, 2015 at 8:51 PM, ttomita notifications@github.com wrote:

>  Wouldn't the signed rank test be more powerful since the Lhats are
> paired?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/52#issuecomment-102555131.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
p = 0.003. We can just mention this in the text?

**Comment by jovo** [comment]
yes! and/or put in title of that panel!

On Friday, May 15, 2015, ttomita notifications@github.com wrote:

>  p = 0.003. We can just mention this in the text?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/52#issuecomment-102566853.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by jovo** [comment]
how did we do with the corrected RerF

On Thursday, May 28, 2015, ttomita notifications@github.com wrote:

>  Closed #52 https://github.com/ttomita/DPForest/issues/52.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/52#event-316407956.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
Lhat_RF > Lhat_RerF: p = 0.99
Lhat_RF < Lhat_RerF: p = 0.03

We did worse :(

**Comment by jovo** [comment]
ok. lets repeat with the faster variant and see how we do?

On Thursday, May 28, 2015, ttomita notifications@github.com wrote:

>  Lhat_RF > Lhat_RerF: p = 0.99
> Lhat_RF < Lhat_RerF: p = 0.03
> 
> We did worse :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/52#issuecomment-106575655.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
