### ISSUE TITLE
interpretability = sparsity

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#60]
RF(total coordiantes) = sum_t (# nodes)

RerF = sum_t (# coordinates per node \* number nodes_t 

2D scatter plot on examples

**Comment by tyler-tomita** [comment]
Interesting. I have to rerun the whole thing on all 121 datasets because I didn't save the classifiers after training the first time. Therefore I don't know how many nodes or what the variables used per node are for the trees. I was initially saving them but noticed that I was rapidly running out of disk space on cis, so I stopped.

**Comment by jovo** [comment]
ah, those last issues that i added were from talking to mauro about your
stuff.
let's catch up tomorrow...

On Tue, May 19, 2015 at 9:11 PM, ttomita notifications@github.com wrote:

>  Interesting. I have to rerun the whole thing on all 121 datasets because
> I didn't save the classifiers after training the first time. Therefore I
> don't know how many nodes or what the variables used per node are for the
> trees. I was initially saving them but noticed that I was rapidly running
> out of disk space on cis, so I stopped.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/60#issuecomment-103710911.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
It's a simple metric but could be very telling.

I'm meeting with Will at 10am, so I'm free 11am onward

**Comment by jovo** [comment]
cool, let's talk around noon.

On Tue, May 19, 2015 at 11:14 PM, ttomita notifications@github.com wrote:

>  It's a simple metric but could be very telling.
> 
> I'm meeting with Will at 10am, so I'm free 11am onward
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/60#issuecomment-103740678.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
