### ISSUE TITLE
Redo Benchmark Data Analysis Using Updated Rank Procedure?

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#61]
In 10 trials, RF with passing to ranks achieved lower Lhat than not passing to ranks 9/10 times. 

Matlab has a function called tiedranks that ranks the data but adjusts for tied ranks by computing the average rank. When I replaced the function I wrote with this function and repeated the 10 trials, there was no longer a difference in Lhats between the two RF variants.

This seems to be evidence that not adjusting for repeated values can significantly alter the structure of the data because values that were the same take on different values in the ranked space. Here's an example to illustrate the problem with this: Imagine a 1D scenario where two points, one from class 0 and one from class 1, have the same value in the original space. Now when ranked without adjusting for ties, one will be mapped to a rank of 1 and the other to a rank of 2. Suddenly they are separable.

**Comment by jovo** [comment]
interesting. ok, lets use tied ranks.
but why does it do better? it seems like if it randomly sorts ties, it
should be the same. seems like it is not randomly sorting ties, which is
the problem.

can u figure out how your current rank function deals with ties?

On Wednesday, May 20, 2015, ttomita notifications@github.com wrote:

>  In 10 trials, RF with passing to ranks achieved lower Lhat than not
> passing to ranks 9/10 times.
> 
> Matlab has a function called tiedranks that ranks the data but adjusts for
> tied ranks by computing the average rank. When I replaced the function I
> wrote with this function and repeated the 10 trials, there was no longer a
> difference in Lhats between the two RF variants.
> 
> This seems to be evidence that not adjusting for repeated values can
> significantly alter the structure of the data because values that were the
> same take on different values in the ranked space. Here's an example to
> illustrate the problem with this: Imagine a 1D scenario where two points,
> one from class 0 and one from class 1, have the same value in the original
> space. Now when ranked without adjusting for ties, one will be mapped to a
> rank of 1 and the other to a rank of 2. Suddenly they are separable.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/61.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by tyler-tomita** [comment]
My rank function just assigns ranks in order of the points. So the vector [1 1 1 1] would be mapped to [1 2 3 4]

**Comment by jovo** [comment]
ah. so if the points are systematically ordered, that is bad.
so, u can either give ties equal rank,
or randomly permute point order.
probably the former is better.

can u re-run all the experiments with equal ranks for ties?

On Wednesday, May 20, 2015, ttomita notifications@github.com wrote:

>  My rank function just assigns ranks in order of the points. So the
> vector [1 1 1 1] would be mapped to [1 2 3 4]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/61#issuecomment-103756619.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
