### ISSUE TITLE
Trunk where RerF doesn't do worse

### ISSUE THREAD

**Issue by tyler-tomita** [ttomita/RandomerForest#62]
Make mean difference times eigenvalues constant
Covariance matrix with 1/meandiff
Fix d to 10 and vary n logarithmically from 10 to 1000

**Comment by tyler-tomita** [comment]
I did the same thing as Fig 1 but instead the diagonals of the covariance matrix d(i) = 1/(mu1(i)-mu0(i))
All RerF variants do slightly better at low d and worse at high d

![trunk_harder_ooberror_vs_d_n100_ntrees1500_ntrials10](https://cloud.githubusercontent.com/assets/9794449/7869591/b1f753de-0551-11e5-8cec-77ff0bcb1c75.png)

**Comment by jovo** [comment]
this is great!
put in appendix for now, and add caption.

On Thursday, May 28, 2015, ttomita notifications@github.com wrote:

>  I did the same thing as Fig 1 but instead the diagonals of the
> covariance matrix d(i) = 1/(mu1(i)-mu0(i))
> All RerF variants do slightly better at low d and worse at high d
> 
> [image: trunk_harder_ooberror_vs_d_n100_ntrees1500_ntrials10]
> https://cloud.githubusercontent.com/assets/9794449/7869591/b1f753de-0551-11e5-8cec-77ff0bcb1c75.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/DPForest/issues/62#issuecomment-106579796.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
