### ISSUE TITLE
rerf vs. FRC

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#76]
https://github.com/ttomita/RandomerForest/blob/master/Figures/png/error_vs_sparsity.png

is this for the setting in which FRC did dramatically better than us?
i think p=1000, n=100?
i don't see why, maybe because i don't understand the figure?
maybe add a legend, make color informative, use different line styles, or something?

**Comment by tyler-tomita** [comment]
FRC didn't do dramatically better than us for this setting (p=1000,n=100). In general it was only about 1% lower than RerF for all Trunk settings. There were a couple settings in sparse parity where it did substantially better. I'll can try one of those settings instead.
The figure is more clear now, I think. mtry is the number of projections sampled at split nodes

**Comment by jovo** [comment]
indeed it does!
yah, please try on the example for which FRC kicked our ass.

On Tue, Mar 8, 2016 at 12:20 PM, Tyler Tomita notifications@github.com
wrote:

> FRC didn't do dramatically better than us for this setting (p=1000,n=100).
> In general it was only about 1% lower than RerF for all Trunk settings.
> There were a couple settings in sparse parity where it did substantially
> better. I'll can try one of those settings instead.
> The figure is more clear now, I think. mtry is the number of projections
> sampled at split nodes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ttomita/RandomerForest/issues/76#issuecomment-193876037
> .

## 

the glass is all full:  half water, half air.
neurodata.io
